adding error handling just in case if git command fails

diff --git a/.github/workflows/get_list_of_files.yml b/.github/workflows/get_list_of_files.yml
--- a/.github/workflows/get_list_of_files.yml
+++ b/.github/workflows/get_list_of_files.yml
@@ -27,5 +27,8 @@ jobs:
             run: |
              echo "Getting list of files changed between ${{ github.head_ref }} and ${{ github.base_ref }}"
              changed_files=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | tr '\n' ' ')
+             if [ $? -ne 0 ]; then
+              echo "Fail to get list of changed files. Please check the error"
+              exit 1
              echo "changed_files=$changed_files" >> $GITHUB_ENV
              echo "Changed Files: $changed_files"
